name: .NET Build & Tag Version

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install GitVersion
        run: |
          dotnet tool install --global GitVersion.Tool --version 5.6.0

      - name: Generate Version Info
        id: version
        run: |
          git fetch --tags
          gitversion /showvariable FullSemVer

      - name: Build Project
        run: |
          dotnet build --configuration Release

      - name: Tag Commit with Version
        run: |
          git tag -a "v${{ steps.version.outputs.FullSemVer }}" -m "Release version"
          git push origin --tags